name = "easytier-ws-relay-worker"
main = "src/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
WS_PATH = ""
EASYTIER_DISABLE_RELAY = "0"
EASYTIER_COMPRESS_RPC = "1"
LOCATION_HINT = "apac"

[durable_objects]
bindings = [
  { name = "RELAY_ROOM", class_name = "RelayRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayRoom"]
